/*
 * bms.h
 *
 *  Created on: Oct 7, 2025
 *      Author: CesarO
 */

#ifndef INC_BMS_H_
#define INC_BMS_H_

typedef enum
{
    ADDR_CONTROL_STATUS       = 0x00,
    ADDR_SAFETY_ALERT_STATUS  = 0x02,    // hasta 0x07
    ADDR_SAFETY_STATUS_A      = 0x03,
    ADDR_SAFETY_STATUS_B      = 0x05,
    ADDR_SAFETY_STATUS_C      = 0x07,
    ADDR_PF_ALERT_STATUS      = 0x0A,    // hasta 0x11
    ADDR_PF_STATUS_A          = 0x0B,
    ADDR_PF_STATUS_B          = 0x0D,
    ADDR_PF_STATUS_C          = 0x0F,
    ADDR_BATTERY_STATUS       = 0x12,
    ADDR_CELL_VOLTAGES        = 0x14,    // hasta 0x32
    ADDR_STACK_VOLTAGE        = 0x34,
    ADDR_PACK_PIN_VOLTAGE     = 0x36,
    ADDR_LD_PIN_VOLTAGE       = 0x38,
    ADDR_CC2_CURRENT          = 0x3A,
    ADDR_ALARM_STATUS         = 0x62,
    ADDR_ALARM_RAW_STATUS     = 0x64,
    ADDR_ALARM_ENABLE         = 0x66,
    ADDR_INTERNAL_TEMP        = 0x68,
    ADDR_THERMISTOR_TEMP      = 0x6A,    // hasta 0x7A
    ADDR_FET_STATUS           = 0x7F,
    ADDR_DEVICE_NUMBER        = 0x0001,
    ADDR_FW_VERSION           = 0x0002,
    ADDR_HW_VERSION           = 0x0003,
    ADDR_IROM_SIG             = 0x0004,
    ADDR_STATIC_CFG_SIG       = 0x0005,
    ADDR_DROM_SIG             = 0x0009,
    ADDR_EXIT_DEEPSLEEP       = 0x000E,
    ADDR_DEEPSLEEP            = 0x000F,
    ADDR_SHUTDOWN             = 0x0010,
    ADDR_RESET                = 0x0012,
    ADDR_PDSGTEST             = 0x001C,
    ADDR_FUSE_TOGGLE          = 0x001D,
    ADDR_PCHGTEST             = 0x001E,
    ADDR_CHGTEST              = 0x001F,
    ADDR_DSGTEST              = 0x0020,
    ADDR_FET_ENABLE           = 0x0022,
    ADDR_PF_ENABLE            = 0x0024,
    ADDR_SEAL                 = 0x0030,
    ADDR_SAVED_PF_STATUS      = 0x0053,
    ADDR_MANUFACTURING_STATUS = 0x0057,
    ADDR_MANU_DATA            = 0x0070,
    ADDR_DASTATUS1            = 0x0071,
    ADDR_DASTATUS2            = 0x0072,
    ADDR_DASTATUS3            = 0x0073,
    ADDR_DASTATUS4            = 0x0074,
    ADDR_DASTATUS5            = 0x0075,
    ADDR_DASTATUS6            = 0x0076,
    ADDR_DASTATUS7            = 0x0077,
    ADDR_CUV_SNAPSHOT         = 0x0080,
    ADDR_COV_SNAPSHOT         = 0x0081,
    ADDR_RESET_PASSQ          = 0x0082,
    ADDR_CB_ACTIVE_CELLS      = 0x0083,
    ADDR_CB_SET_LVL1          = 0x0084,
    ADDR_CBSTATUS1            = 0x0085,
    ADDR_CBSTATUS2            = 0x0086,
    ADDR_CBSTATUS3            = 0x0087,
    ADDR_PTO_RECOVER          = 0x008A,
    ADDR_SET_CFGUPDATE        = 0x0090,
    ADDR_EXIT_CFGUPDATE       = 0x0092,
    ADDR_DSG_PDSG_OFF         = 0x0093,
    ADDR_CHG_PCHG_OFF         = 0x0094,
    ADDR_ALL_FETS_OFF         = 0x0095,
    ADDR_ALL_FETS_ON          = 0x0096,
    ADDR_FET_CONTROL          = 0x0097,
    ADDR_REG12_CONTROL        = 0x0098,
    ADDR_SLEEP_ENABLE         = 0x0099,
    ADDR_SLEEP_DISABLE        = 0x009A,
    ADDR_OCDL_RECOVER         = 0x009B,
    ADDR_SCDL_RECOVER         = 0x009C,
    ADDR_LOAD_DET_RESTART     = 0x009D,
    ADDR_LOAD_DET_ON          = 0x009E,
    ADDR_LOAD_DET_OFF         = 0x009F,
    ADDR_OTP_WR_CHECK         = 0x00A0,
    ADDR_OTP_WRITE            = 0x00A1,
    ADDR_GPO_SUBCOMMANDS      = 0x2800,    // hasta 0x2818
    ADDR_PF_FORCE_A           = 0x2857,
    ADDR_PF_FORCE_B           = 0x29A3,
    ADDR_SWAP_COMM_MODE       = 0x29BC,
    ADDR_SWAP_TO_I2C          = 0x29E7,
    ADDR_SWAP_TO_SPI          = 0x7C35,
    ADDR_SWAP_TO_HDQ          = 0x7C40,
    ADDR_READ_CAL1            = 0xF081
} bms_command_address_t;

/* Approximate time of completion in usec */
typedef enum
{
    TIME_CONTROL_STATUS       = 50,
    TIME_SAFETY_ALERT         = 50,
    TIME_PF_ALERT             = 50,
    TIME_BATTERY_STATUS       = 50,
    TIME_CELL_VOLTAGES        = 50,
    TIME_STACK_VOLTAGE        = 50,
    TIME_PACK_PIN_VOLTAGE     = 50,
    TIME_LD_PIN_VOLTAGE       = 50,
    TIME_CC2_CURRENT          = 50,
    TIME_ALARM_STATUS         = 50,
    TIME_ALARM_RAW_STATUS     = 50,
    TIME_ALARM_ENABLE         = 50,
    TIME_INTERNAL_TEMP        = 50,
    TIME_THERMISTOR_TEMP      = 50,
    TIME_DEVICE_NUMBER        = 400,
    TIME_FW_VERSION           = 400,
    TIME_HW_VERSION           = 400,
    TIME_IROM_SIG             = 8500,
    TIME_STATIC_CFG_SIG       = 450,
    TIME_DROM_SIG             = 650,
    TIME_EXIT_DEEPSLEEP       = 500,
    TIME_DEEPSLEEP            = 500,
    TIME_SHUTDOWN             = 500,
    TIME_PDSGTEST             = 550,
    TIME_FUSE_TOGGLE          = 500,
    TIME_PCHGTEST             = 900,
    TIME_CHGTEST              = 550,
    TIME_DSGTEST              = 550,
    TIME_FET_ENABLE           = 500,
    TIME_PF_ENABLE            = 500,
    TIME_SEAL                 = 500,
    TIME_SAVED_PF_STATUS      = 500,
    TIME_MANUFACTURING_STATUS = 605,
    TIME_MANU_DATA            = 660,
    TIME_DATASTAT1            = 660,
    TIME_CUV_SNAPSHOT         = 660,
    TIME_COV_SNAPSHOT         = 660,
    TIME_RESET_PASSQ          = 600,
    TIME_CB_ACTIVE_CELLS      = 560,
    TIME_CB_SET_LVL1          = 480,
    TIME_CBSTATUS1            = 575,
    TIME_PTO_RECOVER          = 500,
    TIME_SET_CFGUPDATE        = 2000,
    TIME_EXIT_CFGUPDATE       = 1000,
    TIME_DSG_PDSG_OFF         = 550,
    TIME_CHG_PCHG_OFF         = 550,
    TIME_ALL_FETS_OFF         = 550,
    TIME_ALL_FETS_ON          = 500,
    TIME_FET_CONTROL          = 495,
    TIME_REG12_CONTROL        = 450,
    TIME_SLEEP_ENABLE         = 500,
    TIME_SLEEP_DISABLE        = 500,
    TIME_OCDL_RECOVER         = 500,
    TIME_SCDL_RECOVER         = 500,
    TIME_LOAD_DET_RESTART     = 500,
    TIME_LOAD_DET_ON          = 500,
    TIME_LOAD_DET_OFF         = 500,
    TIME_OTP_WR_CHECK         = 580,
    TIME_GPO_SUBCOMMANDS      = 500,
    TIME_PF_FORCE_A           = 500,
    TIME_PF_FORCE_B           = 800,
    TIME_SWAP_COMM_MODE       = 500,
    TIME_SWAP_TO_I2C          = 500,
    TIME_SWAP_TO_SPI          = 500,
    TIME_SWAP_TO_HDQ          = 500,
    TIME_READ_CAL1            = 630
} bms_command_time_t;

#endif /* INC_BMS_H_ */
